// The Docs section. Kept as one file of markup on purpose: it is the part of
// this app a person is most likely to read once, offline, or print — and the
// bounty asks that a developer or an event organiser can use the protocol from
// it without having to ask the contract's author how anything works.

(function (global) {
  "use strict";

  var SECTIONS = [
    ["what", "What an Onchain POAP is"],
    ["quickstart", "Quick start: badge on a wall in ten minutes"],
    ["creating", "Creating a POAP"],
    ["svg", "SVG requirements and optimisation"],
    ["metadata", "What the metadata looks like"],
    ["soulbound", "Soulbound or transferable"],
    ["distribution", "Choosing a distribution method"],
    ["public", "Public minting"],
    ["allowlist", "Allowlists"],
    ["proofs", "Generating allowlist proofs"],
    ["signature", "Signature minting"],
    ["qr", "QR codes for live events"],
    ["deadlines", "Deadlines and creator permissions"],
    ["verify", "Verifying a minted POAP"],
    ["contract", "Contract reference"],
    ["selfhost", "Running this frontend yourself"],
    ["miniapp", "The Farcaster Mini App"]
  ];

  function html(chain) {
    var C = chain();
    var addr = C.contract || "(not deployed on this network)";
    return [
      '<h1>Docs</h1>',
      '<p class="muted">Everything the protocol does, in the order you will need it. ',
      'The contract is the source of truth; where this page states a limit, it is a limit the ',
      'contract enforces, and the number is repeated from <code>src/Poap.sol</code>.</p>',
      '<div class="card"><div class="toc">',
      SECTIONS.map(function (s) { return '<a href="#/docs#' + s[0] + '">' + s[1] + '</a>'; }).join(""),
      '</div></div>',

      '<h2 id="what">What an Onchain POAP is</h2>',
      '<p>A POAP is a badge that says <em>you were there</em>. This one is an ERC-1155 token where the ',
      'artwork and the metadata are not a link to a file — they are bytes in the contract\'s own storage. ',
      'There is no IPFS pin to lapse, no S3 bucket to expire, no metadata server to go down. The image ',
      'is an SVG written with SSTORE2 at registration and read back by <code>uri()</code>, so the ',
      'JSON a marketplace fetches is generated onchain every time it is asked for.</p>',
      '<p>The practical consequence: <b>a POAP cannot rot, and it also cannot be edited.</b> Both halves ',
      'matter. Choose the artwork like you are choosing a tattoo.</p>',
      '<table><tr><th>Property</th><th>Value</th></tr>',
      '<tr><td>Standard</td><td>ERC-1155, one token id per event</td></tr>',
      '<tr><td>Network</td><td>' + C.name + '</td></tr>',
      '<tr><td>Contract</td><td>' + addr + '</td></tr>',
      '<tr><td>Storage</td><td>SSTORE2 (SVG as base64 in contract code)</td></tr>',
      '<tr><td>Supply</td><td>Unlimited holders, exactly one per wallet</td></tr>',
      '<tr><td>Permission</td><td>Anyone may register an event; there is no admin</td></tr></table>',

      '<h2 id="quickstart">Quick start</h2>',
      '<ol class="steps">',
      '<li><b>Draw a badge as an SVG</b> and keep it simple. A circle, a wordmark and a date is plenty ',
      'and costs a few hundred bytes.</li>',
      '<li><b>Open <a href="#/create">Create</a></b>, paste it in, give it a name, tick <em>public ',
      'minting</em>, leave soulbound off unless you are certain.</li>',
      '<li><b>Register.</b> One transaction. You get an event id.</li>',
      '<li><b>Open Manage → Signatures &amp; QR</b> and print the poster. That QR is your entire ',
      'distribution mechanism for a public event.</li>',
      '<li><b>Close public minting</b> when the event ends, from the same Manage page. Anything already ',
      'minted stays minted.</li></ol>',

      '<h2 id="creating">Creating a POAP</h2>',
      '<p><code>registerEvent</code> takes eight parameters and writes them permanently.</p>',
      '<table><tr><th>Field</th><th>Rule</th><th>Changeable later?</th></tr>',
      '<tr><td>name</td><td>Required, 1–128 characters</td><td>Never</td></tr>',
      '<tr><td>description</td><td>Optional, ≤512 characters</td><td>Never</td></tr>',
      '<tr><td>eventDate</td><td>Optional unix timestamp; 0 means unset</td><td>Never</td></tr>',
      '<tr><td>location</td><td>Optional, ≤128 characters, free text</td><td>Never</td></tr>',
      '<tr><td>allowlistRoot</td><td>32 bytes; zero disables</td><td>Once, within 30 days</td></tr>',
      '<tr><td>svgImage</td><td>Required, any length your gas budget tolerates</td><td>Never</td></tr>',
      '<tr><td>externalUrl</td><td>Optional, ≤128 characters</td><td>Never</td></tr>',
      '<tr><td>flags</td><td>0 none · 1 soulbound · 2 public · 3 both</td><td>Public: 30 days. Soulbound: never</td></tr>',
      '</table>',
      '<p>Registration is a single transaction and the gas is dominated by the SVG. On Base Sepolia a ',
      '165-byte SVG registers for about 386,000 gas; the fixed part of that is roughly 150,000 and the ',
      'rest scales with the artwork.</p>',

      '<h2 id="svg">SVG requirements and optimisation</h2>',
      '<p>The image must be an SVG string. It is base64-encoded (which grows it by a third) and written ',
      'into a data contract, so the cost is roughly <b>200 gas per stored byte</b>. Practically:</p>',
      '<ul><li>Under ~2 KB: cheap. This is where a well-drawn badge belongs.</li>',
      '<li>2–10 KB: fine, noticeably more expensive.</li>',
      '<li>Over ~24 KB: you are near the 24,576-byte contract size ceiling that SSTORE2 inherits, and ',
      'registration will fail rather than merely cost a lot.</li></ul>',
      '<p>The Create page optimises automatically — strips comments, editor metadata, XML prologs and ',
      'empty groups, collapses whitespace, rounds coordinates to two decimals and shortens hex colours ',
      '— and shows you the before, the after and an estimate. It is deliberately conservative and bails ',
      'out unchanged if the result would not re-parse. For the last few percent, run your file through ',
      '<a href="https://jakearchibald.github.io/svgomg/" target="_blank" rel="noopener">SVGOMG</a> ',
      '(SVGO in the browser) first and paste the output.</p>',
      '<p>Three things to avoid, all of which the Create page warns about:</p>',
      '<ul><li><b>Embedded raster images.</b> A <code>&lt;image&gt;</code> with a base64 PNG inside is ',
      'the most expensive thing you can put onchain, by an order of magnitude.</li>',
      '<li><b>Scripts.</b> Wallets and marketplaces strip scripted SVGs; yours will render as nothing.</li>',
      '<li><b>External references.</b> A remote font or image reintroduces exactly the dependency that ',
      'made you choose an onchain POAP.</li></ul>',
      '<p>Always include a <code>viewBox</code>. Without one the artwork will not scale into the square ',
      'frames wallets draw it in.</p>',

      '<h2 id="metadata">What the metadata looks like</h2>',
      '<p><code>uri(eventId)</code> returns a <code>data:application/json;base64,…</code> URL. Decoded, ',
      'it is ordinary ERC-1155 metadata whose <code>image</code> is itself a base64 SVG data URL:</p>',
      '<pre><code>{\n  "name": "ETHGlobal Brussels 2026",\n  "description": "…",\n  "image": "data:image/svg+xml;base64,PHN2Zy…",\n  "attributes": [\n    { "trait_type": "Event",               "value": "…" },\n    { "trait_type": "Location",            "value": "…" },\n    { "trait_type": "Date",                "value": "…" },\n    { "trait_type": "EventId",             "value": "7" },\n    { "trait_type": "Multichain EventId",  "value": "eip155:' + C.id + ':' + (C.contract || "0x…").toLowerCase() + ':7" },\n    { "trait_type": "Creator",             "value": "0x…" },\n    { "trait_type": "Soulbound",           "value": "true" }\n  ]\n}</code></pre>',
      '<p>The multichain id follows CAIP-2, so the same event registered on several chains can be ',
      'recognised as the same event across them.</p>',

      '<h3 id="metadata-escaping">A trap worth knowing about: line breaks and quotes</h3>',
      '<p>The contract builds that JSON by concatenating your strings into it, and it does not escape ',
      'them. So a description containing a <b>line break</b> — which any textarea produces, and which ',
      '<code>registerEvent</code> accepts without complaint — lands in the document as a raw newline ',
      'inside a string literal, which is illegal JSON. The same goes for a double quote or a backslash.</p>',
      '<p class="note warn">The result is a POAP that looks fine in the transaction receipt and renders ',
      '<b>blank</b> in anything that calls <code>JSON.parse</code> and gives up — which is most wallets ',
      'and marketplaces. Because the strings are onchain, it cannot be fixed afterwards. At the time of ',
      'writing, <a href="#/event/6">event #6</a> on Base Sepolia is already in exactly this state.</p>',
      '<p>This app handles it at both ends. The Create page detects unsafe characters as you type, ',
      'explains what they will do and offers to clean them — that is the only moment the problem is ',
      'still fixable. And when reading, it repairs the document (escaping the control characters inside ',
      'string literals, then falling back to pulling the image out with a regex) so an already-broken ',
      'POAP still shows its artwork, with a warning saying why other clients will not.</p>',
      '<p>If you are writing your own frontend against this contract, strip <code>\\n</code>, ',
      '<code>\\r</code>, <code>\\t</code>, <code>"</code> and <code>\\</code> from every string before ',
      'you call <code>registerEvent</code>. It is one line and it is permanent either way.</p>',

      '<h2 id="soulbound">Soulbound or transferable</h2>',
      '<p>A soulbound POAP can be minted and burned but never transferred: the contract reverts on any ',
      'transfer where both sides are non-zero. A transferable one is an ordinary ERC-1155 and can be ',
      'sold.</p>',
      '<p><b>This choice is permanent from the moment you register.</b> There is no toggle, not even in ',
      'the 30-day window. Pick soulbound when the badge is a claim about a person — <em>they were ',
      'there</em> — which is what attendance proof usually means. Pick transferable when you want it to ',
      'be collectible, tradeable, or usable as a ticket someone can pass on.</p>',

      '<h2 id="distribution">Choosing a distribution method</h2>',
      '<p>Three routes exist and they solve different problems. This is the decision most people get ',
      'wrong, so:</p>',
      '<table><tr><th>Use</th><th>When</th><th>Who pays gas</th><th>Works from a static QR?</th></tr>',
      '<tr><td>Public</td><td>Open event, anyone present may claim</td><td>The minter</td><td>Yes</td></tr>',
      '<tr><td>Allowlist</td><td>You know the addresses in advance</td><td>The minter</td><td>Yes</td></tr>',
      '<tr><td>Signature</td><td>You do not know the addresses in advance, but want to approve each one</td><td>The minter</td><td><b>No</b></td></tr>',
      '<tr><td>Direct (creatorMint)</td><td>Recipients should do nothing at all</td><td>You</td><td>n/a</td></tr>',
      '</table>',
      '<p>The "no" in that table is the important cell and it is explained under ',
      '<a href="#/docs#qr">QR codes</a>.</p>',

      '<h2 id="public">Public minting</h2>',
      '<p>When public minting is on, any address may call <code>mint(eventId)</code> once. You can turn ',
      'it on and off as often as you like for 30 days, from Manage → Public minting. Closing it does not ',
      'affect POAPs already minted.</p>',
      '<p>The obvious pattern for a real event: open it when the doors open, close it when they shut. ',
      'After 30 days whatever state you left it in is permanent, so if you intend a POAP to stay ',
      'claimable forever, leave public minting <em>on</em> and let the window close.</p>',

      '<h2 id="allowlist">Allowlists</h2>',
      '<p>An allowlist is one 32-byte Merkle root onchain. The list of addresses is never published to ',
      'the chain and never costs gas, so an allowlist of five and an allowlist of fifty thousand cost ',
      'exactly the same to configure.</p>',
      '<p>Two limits from the contract, both hard:</p>',
      '<ul><li>The root may be set <b>exactly once</b>. A second attempt reverts with ',
      '<code>POAP__RootAlreadySet</code>. There is no replacing it, no clearing it, no appending.</li>',
      '<li>It must be set <b>within 30 days</b> of registration.</li></ul>',
      '<p>So: finalise the list before you write the root. If you must add people later, use signature ',
      'minting instead — it needs no onchain change at all.</p>',
      '<p>You can also set the root at registration time by passing it to <code>registerEvent</code>, ',
      'if you already have the list when you create the event.</p>',

      '<h2 id="proofs">Generating allowlist proofs</h2>',
      '<p>Paste addresses into Manage → Allowlist and the app builds the tree, shows the root, and ',
      'checks its own work by verifying a sample proof with the same fold the contract runs. Then it ',
      'gives you a single file:</p>',
      '<pre><code>{\n  "format": "onchain-poaps-allowlist@1",\n  "root": "0x…",\n  "count": 412,\n  "leafEncoding": "keccak256(abi.encodePacked(address))",\n  "pairHashing": "sorted (OpenZeppelin MerkleProof)",\n  "addresses": ["0x…", …],\n  "proofs": { "0x…": ["0x…", "0x…"], … }\n}</code></pre>',
      '<p><b>Publish that file.</b> Put it on your site, in a gist, on IPFS, wherever. It is not secret: ',
      'a proof only works from the address it belongs to, so one public file serves every recipient and ',
      'you never have to send anyone a personalised anything. A visitor opens the event page, loads the ',
      'file, and their browser finds their row.</p>',
      '<p>If you would rather generate proofs yourself, three details decide whether the contract will ',
      'accept them, and each one produces a tree that is perfectly self-consistent and rejected onchain ',
      'if you get it wrong:</p>',
      '<ol><li>The leaf is <code>keccak256(abi.encodePacked(address))</code> — the 20 raw bytes, hashed ',
      '<em>once</em>. Not <code>abi.encode</code> (32 padded bytes), and not the double-hashed leaf that ',
      '<code>@openzeppelin/merkle-tree</code> uses for its standard trees.</li>',
      '<li>Internal nodes hash the pair in ascending byte order, because OpenZeppelin\'s ',
      '<code>_hashPair</code> sorts. The proof therefore carries no left/right flags.</li>',
      '<li>An odd node at any level is promoted unchanged to the next level, not hashed with itself.</li></ol>',
      '<p>With <code>merkletreejs</code> that is ',
      '<code>new MerkleTree(leaves, keccak256, { sortPairs: true })</code>.</p>',

      '<h2 id="signature">Signature minting</h2>',
      '<p>You sign, offchain and free, a message that names three things: the event id, the chain id and ',
      '<em>one recipient address</em>. The contract recovers the signer from that message and lets that ',
      'recipient mint. In Solidity:</p>',
      '<pre><code>keccak256(abi.encodePacked(eventId, block.chainid, msg.sender))\n  .toEthSignedMessageHash()\n  .recover(signature) == events[eventId].creator</code></pre>',
      '<p>Because the recipient is inside the signed message, <b>a signature is useless to anybody else ',
      'and safe to hand out in the clear</b> — you can email it, print it, put it in a URL. Somebody ',
      'stealing it gains nothing, because the contract checks who is calling.</p>',
      '<p>Signature minting is open for <b>37 days</b> after registration (the 30-day creator window plus ',
      'a 7-day grace period) and cannot be extended. It is the right tool when you did not know the ',
      'guest list in advance: someone shows up, gives you an address, you sign, they mint.</p>',
      '<p>Manage → Signatures &amp; QR will batch-sign a pasted list and hand back JSON or a CSV with one ',
      'row per person.</p>',

      '<h2 id="qr">QR codes for live events</h2>',
      '<p>Manage → Signatures &amp; QR generates a QR code for the event page and a printable poster. ',
      'Put it on a screen, a badge, a sticker or a wall. Someone scans it, connects a wallet, mints.</p>',
      '<p>Now the caveat that most write-ups of this pattern skip:</p>',
      '<p class="note warn"><b>A static QR code cannot carry a signature.</b> A signature names one ',
      'address, and a printed square of ink cannot know who is about to scan it. Any design that ',
      'promises a universal "signature QR" is either running a server that holds your signing key, or ',
      'is broken.</p>',
      '<p>So for a live event, the three real options are:</p>',
      '<ol><li><b>Open public minting for the duration</b> and close it when the doors shut. Simplest, and ',
      'right for most events. The trade-off is that anyone who gets the link during that window can ',
      'mint.</li>',
      '<li><b>Publish an allowlist</b> if you know the guest list. The QR points at the event page, the ',
      'allowlist file is public, and proofs are derived in the visitor\'s browser. Fully static, no ',
      'server, restricted to your list.</li>',
      '<li><b>Sign at the door</b> from the Manage page on a phone or laptop, one address at a time or ',
      'in batches during the day.</li></ol>',
      '<p>What a QR code <em>can</em> carry is a per-person signature, if you print per-person QRs — a ',
      'badge, a wristband, a mailed card. The CSV from the batch signer has one row per recipient for ',
      'exactly that.</p>',

      '<h2 id="deadlines">Deadlines and creator permissions</h2>',
      '<table><tr><th>Action</th><th>Who</th><th>Window</th></tr>',
      '<tr><td>registerEvent</td><td>Anyone</td><td>Always</td></tr>',
      '<tr><td>mint</td><td>Anyone</td><td>Whenever public minting is on</td></tr>',
      '<tr><td>allowlistMint</td><td>Anyone with a proof</td><td>Forever, once a root exists</td></tr>',
      '<tr><td>mintWithSignature</td><td>The signed-for address</td><td>37 days after registration</td></tr>',
      '<tr><td>creatorMint</td><td>Creator</td><td>30 days · ≤101 recipients per call</td></tr>',
      '<tr><td>updateAllowlistRoot</td><td>Creator</td><td>30 days · once, ever</td></tr>',
      '<tr><td>updateEventPublic</td><td>Creator</td><td>30 days · unlimited toggles</td></tr></table>',
      '<p>Note the asymmetry that catches people out: <b>allowlist minting never expires</b>, while the ',
      'ability to <em>set</em> the allowlist does. Set a root on day one and people can still mint against ',
      'it years later.</p>',
      '<p>After day 30 the event is frozen except for minting. After day 37 nothing about it can change ',
      'at all, other than public mints continuing if you left them open.</p>',

      '<h2 id="verify">Verifying a minted POAP</h2>',
      '<p>Every event page carries links to the block explorer and to OpenSea, and every successful mint ',
      'in this app shows its transaction hash. To check independently, without trusting this frontend:</p>',
      '<pre><code># does this address hold event 7?\ncast call ' + addr + ' \\\n  "balanceOf(address,uint256)(uint256)" $ADDRESS 7 --rpc-url ' + C.rpc[0] + '\n\n# has it ever claimed (including a burned token)?\ncast call ' + addr + ' \\\n  "hasClaimed(uint256,address)(bool)" 7 $ADDRESS --rpc-url ' + C.rpc[0] + '\n\n# the full metadata, decoded\ncast call ' + addr + ' "uri(uint256)(string)" 7 \\\n  --rpc-url ' + C.rpc[0] + '</code></pre>',
      '<p><code>balanceOf</code> and <code>hasClaimed</code> can disagree, and the difference is ',
      'meaningful: <code>hasClaimed</code> stays true forever even if the holder later burns or ',
      'transfers a non-soulbound POAP. For "was this person there?", read <code>hasClaimed</code>.</p>',

      '<h2 id="contract">Contract reference</h2>',
      '<p>Source: <a href="https://github.com/jvaleskadevs/onchain-poaps" target="_blank" rel="noopener">',
      'jvaleskadevs/onchain-poaps</a>. Deployment on ' + C.name + ': <code>' + addr + '</code>' +
      (C.contract ? ' — <a href="' + C.explorer + '/address/' + C.contract + '#code" target="_blank" rel="noopener">verified source</a>' : '') + '.</p>',
      '<p>Custom errors, and what each one actually means when you hit it:</p>',
      '<table><tr><th>Error</th><th>Meaning</th></tr>',
      '<tr><td>POAP__InvalidValue(field)</td><td>A parameter broke a length or range rule; the field is named</td></tr>',
      '<tr><td>POAP__TimeLockExpired</td><td>The 30-day creator window has closed</td></tr>',
      '<tr><td>POAP__OnlyCreator</td><td>You are not the address that registered the event</td></tr>',
      '<tr><td>POAP__AlreadyClaimed</td><td>One per wallet; this one already has it</td></tr>',
      '<tr><td>POAP__EventNotPublic</td><td>Public minting is off</td></tr>',
      '<tr><td>POAP__AllowlistNotEnabled</td><td>No root has been set for this event</td></tr>',
      '<tr><td>POAP__RootAlreadySet</td><td>The allowlist root is already set and is not replaceable</td></tr>',
      '<tr><td>POAP__SoulboundNotTransferable</td><td>Soulbound tokens cannot move between wallets</td></tr></table>',
      '<p>This app decodes all of these into sentences rather than showing you a four-byte selector.</p>',

      '<h2 id="selfhost">Running this frontend yourself</h2>',
      '<p>There is no build step, no bundler, no package manager and no server-side anything. The whole ',
      'app is static files that a browser can open directly.</p>',
      '<pre><code>git clone https://github.com/agentatwork/onchain-poaps-app\ncd onchain-poaps-app\npython3 -m http.server 8080\n# → http://localhost:8080</code></pre>',
      '<p>Deploy by copying the directory to any static host, or pinning it to IPFS. Every dependency ',
      '(ethers, the QR encoder, the Farcaster Mini App SDK) is vendored in <code>vendor/</code>, so the ',
      'app has no runtime CDN calls and keeps working if any of those CDNs stop existing.</p>',
      '<p>To point it at a different deployment or a new chain, add a row to <code>CHAINS</code> in ',
      '<code>js/poap.js</code>. Nothing else in the codebase is chain-aware.</p>',
      '<p>The test suite runs the real contract on a fork of Base Sepolia — no faucet, no mocks:</p>',
      '<pre><code>curl -L https://foundry.paradigm.xyz | bash &amp;&amp; foundryup   # provides anvil\nnpm i ethers\nnode test/e2e.js</code></pre>',

      '<h2 id="miniapp">The Farcaster Mini App</h2>',
      '<p>The same files serve as a Farcaster Mini App. Inside a Farcaster client the app detects the ',
      'host, connects the user\'s Farcaster wallet without a prompt, greets them by username, and offers ',
      'to compose a cast after a successful mint. Outside one it is an ordinary website and the ',
      'Farcaster code paths never run.</p>',
      '<p>The manifest lives at <code>/.well-known/farcaster.json</code> and the embed metadata is the ',
      '<code>fc:miniapp</code> meta tag in <code>index.html</code>. If you fork this, both need your own ',
      'domain — a manifest is bound to the domain that serves it, and an account association signed for ',
      'someone else\'s domain will not validate.</p>'
    ].join("");
  }

  global.renderDocs = function (root, ctx) {
    root.innerHTML = html(ctx.chain);
  };
})(window);
